gphelp:
  Title: "§bGP领地指令帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§b/gp del  §6- 查看领地删除相关指令"
  - "§b/gp sw  §6- 查看模式切换相关指令"
  - "§b/gp msg  §6- 查看设定消息相关指令"
  - "§b/gp buy  §6- 查看可购买的领地"
  - "§b/gp sell  §6- 出售当前领地"
  - "§b/gp buyb  §6- 购买领地块"
  - "§b/gp sellb  §6- 出售领地块"
  - "§b/gp tran  §6- 转让当前领地"
  - "§b/gp pet  §6- 转让当前领地驯养动物"
  - "§b/gp name  §6- 修改当前领地名字"
  - "§b/gp tr  §6- 查看信任系统帮助"
  - "§b/gp flags  §6- 打开领地Flag属性聊天GUI"
  - "§b/gp set  §6- 查看修改Flag帮助"
  - "§b/gp pset  §6- 查看修改玩家Flag帮助"
  - "§b/gp gset  §6- 查看修改权限组Flag帮助"
  - "§b/gp reset  §6- 重置领地Flag属性为默认值"
  - "§b/gp playerinfo  §6- 查看自己信息"
  - "§b/gp playerinfo <玩家> [世界]  §6- 查看指定玩家信息"
  - "§b/gp tp §6- 查看传送功能帮助"
  - "§b/gp list  §6- 查看领地列表"
  - "§b/gp list <玩家> [世界]  §6- 查看指定领地列表"
  - "§b/gp info  §6- 查看所在领地信息"
  - "§b/gp info <领地名>  §6- 查看指定领地信息"
  - "§b/gp ignore  §6- 查看聊天屏蔽帮助"
  - "§c/gpa  §6- 查看管理员指令列表"
gpadmin:
  Title: "§bGP管理员指令帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7<必填>  [选填]"
  - "§e/gpa acb <玩家名> <数值> [世界] §f- 增加/减去指定玩家的领地块认领上限"
  - "§e/gpa scb <玩家名> <数值> [世界] §f- 设置指定玩家的领地块认领上限"
  - "§e/gpa sw debugflags §f- 切换到领地debugflags模式"
  - "§e/gpa sw aclaim §f- 切换到管理员圈地模式（可直接使用 /ac）"
  - "§e/gpa sw iclaim §f- 切换到无视领地模式（可直接使用 /ic）"
  - "§e/gpa sw rn §f- 切换到复原领地模式（可直接使用 /rn）"
  - "§e/gpa sw rna §f- 切换到激进复原领地模式（可直接使用 /rna）"
  - "§e/gpa sw rnf [半径] §f- 切换到填补领地模式（可直接使用 /rnf）"
  - "§e/gpa del claim §f- 强制删除你所在的领地"
  - "§e/gpa del allclaims <玩家名> §f- 强制删除指定玩家的所有领地"
  - "§e/gpa del adminclaim §f- 强制删除所有管理员领地"
  - "§e/gpa kill <实体ID> [领地] [世界] §f- 删除领地内指定的实体"
  - "§e/gpa drops §f- 允许玩家拾起你死亡掉落的物品"
  - "§e/gpa ig sep <玩家1> <玩家2> §f- 强制让两位玩家相互屏蔽"
  - "§e/gpa ig unsep <玩家1> <玩家2> §f- 取消两位玩家相互屏蔽"
  - "§e/gpa ig smute <玩家名> §f- 切换指定玩家软禁言（软禁言只能同软禁言玩家聊天）"
  - "§e/gpa reload §f- 重载GP领地插件"
gpignore:
  Title: "§bGP屏蔽功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp ignore ?"
  - "§6请在后面指定一个参数: §c[list] [do] [undo]"
  - "§a/gp ignore list §e- 查看屏蔽聊天玩家列表"
  - "§a/gp ignore do <玩家名> §e- 屏蔽指定玩家的聊天消息"
  - "§a/gp ignore undo <玩家名> §e- 取消屏蔽指定玩家的聊天消息"
  - "§c/gpa ignore sep <玩家1> <玩家2> §e- 强制让两位玩家相互屏蔽"
  - "§c/gpa ignore unsep <玩家1> <玩家2> §e- 取消两位玩家相互屏蔽"
  - "§c/gpa ignore smute <玩家名> §e- 切换指定玩家软禁言（软禁言只能同软禁言玩家聊天）"
  - "-"
  - "§7§lTips:"
  - "§7你也可以将 ignore 简写为 ig"
gpdelete:
  Title: "§bGP删除功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp delete ?"
  - "§6请在后面指定一个参数: §c[claim] [allclaims] [topclaim]"
  - "§a/gp delete claim §e- 删除您所在的领地"
  - "§a/gp delete allclaims §e- 删除您的所有领地"
  - "§a/gp delete topclaim §e- 删除您所在的领地以及子领地"
  - "§c/gpa delete claim §e- 强制删除你所在的领地"
  - "§c/gpa delete allclaims <玩家名> §e- 强制删除指定玩家的所有领地"
  - "§c/gpa delete adminclaim §e- 强制删除所有管理员领地"
  - "-"
  - "§7§lTips:"
  - "§7你也可以将 delete 简写为 del"
  - "§7你也可以将 delete 改写为 remove"
gpswitch:
  Title: "§bGP切换功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp switch ?"
  - "§6请在后面指定一个参数: §c[basic] [sub] [inherit]"
  - "§a/gp switch basic §e- 切换到基础圈地模式（basic 可简写为 bc）"
  - "§a/gp switch sub §e- 切换到圈子领地模式"
  - "§a/gp switch inherit §e- 切换到子领地继承模式"
  - "§c/gpa switch debugflags §e- 切换到领地debugflags模式"
  - "§c/gpa switch aclaim §e- 切换到管理员圈地模式（aclaim 可简写为 ac）"
  - "§c/gpa switch iclaim §e- 切换到无视领地模式（iclaim 可简写为 ic）"
  - "-"
  - "§7§lTips:"
  - "§7你也可以将 switch 简写为 sw"
  - "§7你也可以将 switch 改写为 toggle"
  - "§7你也可以直接使用 /bc /ac /ic"
gpmsgset:
  Title: "§bGP消息功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp msg ?"
  - "§6请在后面指定一个参数: §c[in] [out]"
  - "§a/gp msg in <消息> §e- 玩家进入您领地时显示的消息"
  - "§a/gp msg out <消息> §e- 玩家离开您领地时显示的消息"
  - "-"
  - "§7§lTips:"
  - "§7如果不填写 <消息> 则代表删除提示语"
gpteleport:
  Title: "§bGP传送功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp tp ?"
  - "§6请在后面添加参数: §c<玩家名> <领地名>"
  - "§a/gp tp <玩家名> <领地名> §e- 传送到其他玩家的领地"
  - "-"
  - "§7§lTips:"
  - "§7如果不填写 <玩家名> 则代表传送到自己的领地"
  - "§7由于GP允许领地同名，因此需要填写玩家名"
  - "§7可以使用 /gp list 查看自己的领地列表"
gpsellclaim:
  Title: "§bGP销售功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp sell ?"
  - "§6请在后面添加参数: §c<价格>"
  - "§a/gp sell <价格> §e- 以指定的价格出售你所在的领地"
  - "-"
  - "§7§lTips:"
  - "§7如果 <价格> 为 -1 则代表取消出售领地"
gpbuysellblock:
  Title: "§bGP领地块功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp sellblock ?"
  - "§6请在后面添加参数: §c<数量>"
  - "§a/gp sellblock <数量> §e- 以指定的数量售出你拥有的领地块给服务器"
  - "§a/gp buyblock <数量> §e- 以指定的数量向服务器购买领地块"
  - "§c/gpa acb <玩家名> <数值> [世界] §6- 增加/减去指定玩家的领地块认领上限"
  - "§c/gpa scb <玩家名> <数值> [世界] §6- 设置指定玩家的领地块认领上限"
  - "-"
  - "§7§lTips:"
  - "§7你也可以将 sellblock 简写为 sellb"
  - "§7你也可以将 buyblock 简写为 buyb"
gptransfer:
  Title: "§bGP转让功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp transfer ?"
  - "§6请在后面添加参数: §c<玩家名>"
  - "§a/gp transfer <玩家名> §e- 将你所在的领地转让给指定玩家"
  - "-"
  - "§7§lTips:"
  - "§7你也可以将 transfer 简写为 tran"
  - "§7此操作不可逆，请谨慎"
gppet:
  Title: "§bGP转让功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp pet ?"
  - "§6请在后面指定一个参数: §c<玩家名> [cancel]"
  - "§a/gp pet <玩家名> §e- 将你驯养的宠物转让给指定玩家"
  - "§a/gp pet cancel §e- 将你驯养的宠物放生"
  - "-"
  - "§7§lTips:"
  - "§7此操作不可逆，请谨慎"
gpname:
  Title: "§bGP更名功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp rename ?"
  - "§6请在后面添加参数: §c<名字>"
  - "§a/gp rename <名字> §e- 更改你所在领地的名字"
  - "-"
  - "§7§lTips:"
  - "§7你也可以将 rename 简写为 name"
gpplayerinfo:
  Title: "§bGP信息功能帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp playerinfo ?"
  - "§6请在后面按顺序添加参数: §c<玩家名> §c<世界>"
  - "§a/gp playerinfo <玩家名> §e- 查看指定玩家信息"
  - "§a/gp playerinfo <玩家名> <世界> §e- 查看指定玩家指定世界信息"
  - "§7§lTips:"
  - "§7你也可以将 playerinfo 简写为 pinfo"
gpcf:
  Title: "§bGP领地Flags帮助"
  Padding: "-"
  Page: 20
  Contents: 
  - "§7/gp set ? §7/cf ? §7/gp cf ?"
  - "§6请在后面按顺序添加参数: §c<Flags> §7<触发者> §c<目标> §c<布尔> §7[override]|§7[default] §7<原因>"
  - "§c<Flags> §a相关值的信息请查看下一页"
  - "§7<触发者> §a指的是事件或者动作的触发者，例如§f minecraft:player §a。这一项为选填。"
  - "§c<目标> §a被影响的目标，例如 §fminecraft:dirt §a。使用 §fany §a或者 §fModid:any §a，指游戏所有东西或某个模组的所有东西。"
  - "§c<布尔> §a在这里填 §ftrue §a或者 §ffalse §a，指允许或禁止这条 Flag §a，如果填 §f0 §a则移除这条 Flag 。"
  - "§7[override] §a意思是会把此flag生效于所有同类的领地上，§7[default] §a意思是会把此 Flag 生效于所有新的同类领地上。这一项为选填。"
  - "§7<原因> §a将会把禁止原因发送给触发相应事件的玩家。这一项为选填。"
  - "-"
  - "§7§lTips:"
  - "  §7你也可以将 gp set 改写为 cf。"
  - "  §7建议直接使用原生的 /cf ，这样可以在输入 Flags 时使用 tab 检索功能。"
  - "  §7参数里灰色部分是选填，而红色部分是必填。"
  - "  §7管理员可在非领地的地方使用此功能，可直接设置所在世界的 Flag 值，如果填了 [override] 则是设置整个服务器的 Flag 值。"
  - "§e§l例如:"
  - "  §3你不想让任何人§l右键§3（不是破坏）你领地的方块，比如工业扳手，则输入:"
  - "  §f/cf §ainteract-block-secondary §cany §dfalse §f不要碰我的方块"
  - "  §3你不想让任何人在你的领地放置泥土方块则输入:"
  - "  §f/cf §ablock-place §cminecraft:dirt §dfalse"
  - "-"
  - "§b下列为所有 Flag 值 §7（下方括号里的是例子）"
  - "§a block-break §e- 用来管理破坏方块(允许破坏泥土方块)"
  - "§a block-place §e- 用了管理放置方块 (允许放置泥土方块)"
  - "§a command-execute §e- 用来管理执行指令 (Doing /msg inside claim)"
  - "§a command-execute-pvp §e- 用来管理战斗状态下执行指令 (是否可以在PVP状态下使用 /tp )"
  - "§a enter-claim §e- 用来管理进入领地(不允许一个任意的玩家进入领地)"
  - "§a collide-block §e- 用来管理同方块的碰触 (同砖块的碰触)"
  - "§a collide-entity §e- 用来管理同生物的碰触 (同一个野生米二碰触)"
  - "§a entity-damage §e- 用来管理来自生物的伤害判定 (僵尸攻击任意玩家)"
  - "§a entity-riding §e- 用来管理生物的骑乘 (骑马、坐船、坐矿车等等)"
  - "§a entity-spawn §e-用来控制生物的生成 (这包含任意的生成方式，包含区块的自然生成怪物)"
  - "§a entity-teleport-from §e- 用来管理生物传送出领地 (一个末影人从领地传送出去)"
  - "§a entity-teleport-to §e- 用来管理生物传送到领地 (一个末影人传送到领地内)"
  - "§a exit-claim §e- 用来管理退出领地 (不允许任何的玩家走出领地)"
  - "§a explosion §e- 用来管理爆炸 (TNT在任何位置爆炸。因暂时有BUG，无法防御地表上的爆炸)"
  - "§a explosion-surface §e- 用来管理在地表或者上空的爆炸 (TNT在地面或者空中爆炸)"
  - "§a fire-spread §e- 用来管理火焰蔓延 (火在木头上的蔓延)"
  - "§a interact-block-primary §e- 用来管理同方块左键交互 (左键龙蛋)"
  - "§a interact-block-secondary §e- 用来管理同方块右键交互 (打开Pixelmon的个人电脑、ic2扳手拆方块)"
  - "§a interact-entity-primary §e- 用来管理同生物左键交互 (杀鸡)"
  - "§a interact-entity-secondary §e- 用来管理同生物右键交互(喂鸡)"
  - "§a interact-inventory §e- 用来管理打开物品栏 (允许打开箱子)"
  - "§a interact-inventory-click §e- 用来管理同物品栏的物品交互. (禁止合成)"
  - "§a interact-item-primary §e- 用来管理同物品进行左键交互 ()"
  - "§a interact-item-secondary §e- 用来管理同物品进行右键交互 (吃东西、使用模组工具、使用模组法杖)"
  - "§a item-drop §e- 用来管理玩家丢弃物品 (玩家不能丢弃泥土方块)"
  - "§a item-pickup §e- 用来管理拾取被丢弃的物品 (玩家不能拾取被丢弃出来的泥土块)"
  - "§a item-spawn §e- 用来管理从方块或物品中生成物品 (例如Pixelmon的礼盒)"
  - "§a item-use §e- 用来管理使用物品 (玩家使用药水|末影珍珠|经验瓶)"
  - "§a leaf_decay §e- 用来管理岩浆是否衰退（控制岩浆是否会消失）"
  - "§a liquid-flow §e- 用来管理液体流动 (控制水或者岩浆的流动)"
  - "§a portal-use §e- 用来管理使用传送门 (控制使用地狱传送门)"
  - "§a projectile-impact-block §e- 用来管理弹射物射击方块 (禁止用弓箭射击泥土块)"
  - "§a projectile-impact-entity §e- 用来管理弹射物伤害生物 (禁止用弓箭伤害动物)"
  - "-"
  - "§acf/set 编辑所在领地 Flag ，§ecfp/pset 编辑所在领地指定玩家 Flag ，§3cfg/gset 编辑所在领地指定用户组 Flag ，§ccfr 重置所在领地的 Flag 值"
gpcfp:
  Title: "§bGP领地Flags帮助"
  Padding: "-"
  Page: 20
  Contents: 
  - "§7/gp pset ? §7/cfp ? §7/gp cfp ?"
  - "§6请在后面按顺序添加参数: §c<玩家名> §c<Flags> §7<触发者> §c<目标> §c<布尔> §7[override]|§7[default] §7<原因>"
  - "§c<玩家名> §e- 指定玩家ID"
  - "§c<Flags> §a相关值的信息请查看下一页"
  - "§7<触发者> §a指的是事件或者动作的触发者，例如§f minecraft:player §a。这一项为选填。"
  - "§c<目标> §a被影响的目标，例如 §fminecraft:dirt §a。使用 §fany §a或者 §fModid:any §a，指游戏所有东西或某个模组的所有东西。"
  - "§c<布尔> §a在这里填 §ftrue §a或者 §ffalse §a，指允许或禁止这条 Flag §a，如果填 §f0 §a则移除这条 Flag 。"
  - "§7[override] §a意思是会把此flag生效于所有同类的领地上，§7[default] §a意思是会把此 Flag 生效于所有新的同类领地上。这一项为选填。"
  - "§7<原因> §a将会把禁止原因发送给触发相应事件的玩家。这一项为选填。"
  - "-"
  - "§7§lTips:"
  - "  §7单独使用 /gp pset <玩家名> 可以打开聊天界面直接编辑他现有此领地的 Flags 值"
  - "  §7你也可以将 gp pset 改写为 cfp。"
  - "  §7建议直接使用原生的 /cfp ，这样可以在输入 Flags 时使用 tab 检索功能。"
  - "  §7参数里灰色部分是选填，而红色部分是必填。"
  - "  §7管理员可在非领地的地方使用此功能，可直接设置所在世界的 Flag 值，如果填了 [override] 则是设置整个服务器的 Flag 值。"
  - "-"
  - "§b下列为所有 Flag 值 §7（下方括号里的是例子）"
  - "§a block-break §e- 用来管理破坏方块(允许破坏泥土方块)"
  - "§a block-place §e- 用了管理放置方块 (允许放置泥土方块)"
  - "§a command-execute §e- 用来管理执行指令 (Doing /msg inside claim)"
  - "§a command-execute-pvp §e- 用来管理战斗状态下执行指令 (是否可以在PVP状态下使用 /tp )"
  - "§a enter-claim §e- 用来管理进入领地(不允许一个任意的玩家进入领地)"
  - "§a collide-block §e- 用来管理同方块的碰触 (同砖块的碰触)"
  - "§a collide-entity §e- 用来管理同生物的碰触 (同一个野生米二碰触)"
  - "§a entity-damage §e- 用来管理来自生物的伤害判定 (僵尸攻击任意玩家)"
  - "§a entity-riding §e- 用来管理生物的骑乘 (骑马、坐船、坐矿车等等)"
  - "§a entity-spawn §e-用来控制生物的生成 (这包含任意的生成方式，包含区块的自然生成怪物)"
  - "§a entity-teleport-from §e- 用来管理生物传送出领地 (一个末影人从领地传送出去)"
  - "§a entity-teleport-to §e- 用来管理生物传送到领地 (一个末影人传送到领地内)"
  - "§a exit-claim §e- 用来管理退出领地 (不允许任何的玩家走出领地)"
  - "§a explosion §e- 用来管理爆炸 (TNT在任何位置爆炸。因暂时有BUG，无法防御地表上的爆炸)"
  - "§a explosion-surface §e- 用来管理在地表或者上空的爆炸 (TNT在地面或者空中爆炸)"
  - "§a fire-spread §e- 用来管理火焰蔓延 (火在木头上的蔓延)"
  - "§a interact-block-primary §e- 用来管理同方块左键交互 (左键龙蛋)"
  - "§a interact-block-secondary §e- 用来管理同方块右键交互 (打开Pixelmon的个人电脑、ic2扳手拆方块)"
  - "§a interact-entity-primary §e- 用来管理同生物左键交互 (杀鸡)"
  - "§a interact-entity-secondary §e- 用来管理同生物右键交互(喂鸡)"
  - "§a interact-inventory §e- 用来管理打开物品栏 (允许打开箱子)"
  - "§a interact-inventory-click §e- 用来管理同物品栏的物品交互. (禁止合成)"
  - "§a interact-item-primary §e- 用来管理同物品进行左键交互 ()"
  - "§a interact-item-secondary §e- 用来管理同物品进行右键交互 (吃东西、使用模组工具、使用模组法杖)"
  - "§a item-drop §e- 用来管理玩家丢弃物品 (玩家不能丢弃泥土方块)"
  - "§a item-pickup §e- 用来管理拾取被丢弃的物品 (玩家不能拾取被丢弃出来的泥土块)"
  - "§a item-spawn §e- 用来管理从方块或物品中生成物品 (例如Pixelmon的礼盒)"
  - "§a item-use §e- 用来管理使用物品 (玩家使用药水|末影珍珠|经验瓶)"
  - "§a leaf_decay §e- 用来管理岩浆是否衰退（控制岩浆是否会消失）"
  - "§a liquid-flow §e- 用来管理液体流动 (控制水或者岩浆的流动)"
  - "§a portal-use §e- 用来管理使用传送门 (控制使用地狱传送门)"
  - "§a projectile-impact-block §e- 用来管理弹射物射击方块 (禁止用弓箭射击泥土块)"
  - "§a projectile-impact-entity §e- 用来管理弹射物伤害生物 (禁止用弓箭伤害动物)"
  - "-"
  - "§acf/set 编辑所在领地 Flag ，§ecfp/pset 编辑所在领地指定玩家 Flag ，§3cfg/gset 编辑所在领地指定用户组 Flag ，§ccfr 重置所在领地的 Flag 值"
gpcfg:
  Title: "§bGP领地Flags帮助"
  Padding: "-"
  Page: 20
  Contents: 
  - "§7/gp gset ? §7/cfg ? §7/gp cfg ?"
  - "§6请在后面按顺序添加参数: §c<组名> §c<Flags> §7<触发者> §c<目标> §c<布尔> §7[override]|§7[default] §7<原因>"
  - "§c<组名> §e- 指定某个权限组的名字"
  - "§c<Flags> §a相关值的信息请查看下一页"
  - "§7<触发者> §a指的是事件或者动作的触发者，例如§f minecraft:player §a。这一项为选填。"
  - "§c<目标> §a被影响的目标，例如 §fminecraft:dirt §a。使用 §fany §a或者 §fModid:any §a，指游戏所有东西或某个模组的所有东西。"
  - "§c<布尔> §a在这里填 §ftrue §a或者 §ffalse §a，指允许或禁止这条 Flag §a，如果填 §f0 §a则移除这条 Flag 。"
  - "§7[override] §a意思是会把此flag生效于所有同类的领地上，§7[default] §a意思是会把此 Flag 生效于所有新的同类领地上。这一项为选填。"
  - "§7<原因> §a将会把禁止原因发送给触发相应事件的玩家。这一项为选填。"
  - "-"
  - "§7§lTips:"
  - "  §7你也可以将 gp gset 改写为 cfg。"
  - "  §7建议直接使用原生的 /cfg ，这样可以在输入 Flags 时使用 tab 检索功能。"
  - "  §7参数里灰色部分是选填，而红色部分是必填。"
  - "  §7管理员可在非领地的地方使用此功能，可直接设置所在世界的 Flag 值，如果填了 [override] 则是设置整个服务器的 Flag 值。"
  - "-"
  - "§b下列为所有 Flag 值 §7（下方括号里的是例子）"
  - "§a block-break §e- 用来管理破坏方块(允许破坏泥土方块)"
  - "§a block-place §e- 用了管理放置方块 (允许放置泥土方块)"
  - "§a command-execute §e- 用来管理执行指令 (Doing /msg inside claim)"
  - "§a command-execute-pvp §e- 用来管理战斗状态下执行指令 (是否可以在PVP状态下使用 /tp )"
  - "§a enter-claim §e- 用来管理进入领地(不允许一个任意的玩家进入领地)"
  - "§a collide-block §e- 用来管理同方块的碰触 (同砖块的碰触)"
  - "§a collide-entity §e- 用来管理同生物的碰触 (同一个野生米二碰触)"
  - "§a entity-damage §e- 用来管理来自生物的伤害判定 (僵尸攻击任意玩家)"
  - "§a entity-riding §e- 用来管理生物的骑乘 (骑马、坐船、坐矿车等等)"
  - "§a entity-spawn §e-用来控制生物的生成 (这包含任意的生成方式，包含区块的自然生成怪物)"
  - "§a entity-teleport-from §e- 用来管理生物传送出领地 (一个末影人从领地传送出去)"
  - "§a entity-teleport-to §e- 用来管理生物传送到领地 (一个末影人传送到领地内)"
  - "§a exit-claim §e- 用来管理退出领地 (不允许任何的玩家走出领地)"
  - "§a explosion §e- 用来管理爆炸 (TNT在任何位置爆炸。因暂时有BUG，无法防御地表上的爆炸)"
  - "§a explosion-surface §e- 用来管理在地表或者上空的爆炸 (TNT在地面或者空中爆炸)"
  - "§a fire-spread §e- 用来管理火焰蔓延 (火在木头上的蔓延)"
  - "§a interact-block-primary §e- 用来管理同方块左键交互 (左键龙蛋)"
  - "§a interact-block-secondary §e- 用来管理同方块右键交互 (打开Pixelmon的个人电脑、ic2扳手拆方块)"
  - "§a interact-entity-primary §e- 用来管理同生物左键交互 (杀鸡)"
  - "§a interact-entity-secondary §e- 用来管理同生物右键交互(喂鸡)"
  - "§a interact-inventory §e- 用来管理打开物品栏 (允许打开箱子)"
  - "§a interact-inventory-click §e- 用来管理同物品栏的物品交互. (禁止合成)"
  - "§a interact-item-primary §e- 用来管理同物品进行左键交互 ()"
  - "§a interact-item-secondary §e- 用来管理同物品进行右键交互 (吃东西、使用模组工具、使用模组法杖)"
  - "§a item-drop §e- 用来管理玩家丢弃物品 (玩家不能丢弃泥土方块)"
  - "§a item-pickup §e- 用来管理拾取被丢弃的物品 (玩家不能拾取被丢弃出来的泥土块)"
  - "§a item-spawn §e- 用来管理从方块或物品中生成物品 (例如Pixelmon的礼盒)"
  - "§a item-use §e- 用来管理使用物品 (玩家使用药水|末影珍珠|经验瓶)"
  - "§a leaf_decay §e- 用来管理岩浆是否衰退（控制岩浆是否会消失）"
  - "§a liquid-flow §e- 用来管理液体流动 (控制水或者岩浆的流动)"
  - "§a portal-use §e- 用来管理使用传送门 (控制使用地狱传送门)"
  - "§a projectile-impact-block §e- 用来管理弹射物射击方块 (禁止用弓箭射击泥土块)"
  - "§a projectile-impact-entity §e- 用来管理弹射物伤害生物 (禁止用弓箭伤害动物)"
  - "-"
  - "§acf/set 编辑所在领地 Flag ，§ecfp/pset 编辑所在领地指定玩家 Flag ，§3cfg/gset 编辑所在领地指定用户组 Flag ，§ccfr 重置所在领地的 Flag 值"
gptrust:
  Title: "§bGP领地信任系统帮助"
  Padding: "-"
  Page: 15
  Contents: 
  - "§7/gp ?"
  - "§a /gp at <玩家名>  §e- 授予玩家进入你的领地和与床进行交互的权限"
  - "§a /gp ct <玩家名>  §e- 授予玩家进入你的领地和与容器、庄稼、动物、床、按钮和杠杆进行交互的权限"
  - "§a /gp pt <玩家名>  §e- 授予玩家授予他人权限的权限"
  - "§a /gp t <玩家名>  §e- 授予玩家当前领地的最高使用权限"
  - "§a /gp ut <玩家名>  §e- 将指定玩家从你领地的trust列表中移除"
  - "§a /gp ta <玩家名>  §e- 授予玩家你所有领地的最高使用权限"
  - "§a /gp uta <玩家名>  §e- 将指定玩家从你所有领地的trust列表中移除"
  - "§a /gp tlist  §e- 列出当前领地的trust授权玩家"
  - "§7§lTips:"
  - "§7你也可以将上列每条命令开头的 gp 去除掉"
  - "§7<玩家名> 处输入 §npublic§7 即信任所有人"
a2:
  Title: "标题"
  Padding: "-"
  Page: 1
  Contents: 
  - "测试"
  - "测试2"